MODULE MPL_MODULE

    ! hhalonen

    USE mo_kind, ONLY: dp
    IMPLICIT NONE
    CONTAINS
    SUBROUTINE MPL_BROADCAST(lut,KTAG,KROOT,CDSTRING)
        IMPLICIT NONE
        REAL(dp) :: lut(:,:,:)
        INTEGER :: KTAG, KROOT
        CHARACTER (len=64) :: CDSTRING
    END SUBROUTINE MPL_BROADCAST
END MODULE MPL_MODULE
